all:
  children:
    oracle:
      hosts:
        fido.stupidzombie.com:
          vars:
            ip: 129.213.145.8
            virtual_instance: josevnz-server1
        solomon.stupidzombie.com:
          vars:
            ip: XXX.YYY.ZZZ.AAA
            virtual_instance: josevnz-server2
      vars:
        remote_user: opc
        description: |-
          Oracle Cloud virtual machines (free tier).
          Remote access: ssh opc@XXX.YYY.ZZZ.AAA.
          Requires public SSH key on https://cloud.oracle.com/
    controllers:
      hosts:
        fido.stupidzombie.com: