---
# You should really read this: https://fedoraproject.org/wiki/Firewalld
# Open the Prometheus scrapper port, so we can check stats from the Internet. In production, you may want to protect this through a VPN.
# You can check with: for zones in for zones in $(firewall-cmd --get-active-zones|grep -v interfaces); do firewall-cmd --zone $zones --list-all; done
- name: Enable Prometheus at the Linux firewall, all clients
  ansible.posix.firewalld:
    zone: public
    port: "{{ prometheus_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  run_once: true
  delegate_to: "{{ controller_host }}"
  notify:
    - Reload firewall
  tags: prometheus_firewall

- name: Get Prometheus scrapper
  vars:
    github_prom: "https://github.com/prometheus/prometheus/releases/download"
  ansible.builtin.get_url:
    url: "{{ github_prom }}/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ architecture }}.tar.gz"
    dest: "/opt/prometheus-{{ prometheus_version }}.linux-{{ architecture }}.tar.gz"
    mode: u=rw,g=r,o=-rwx
  run_once: true
  delegate_to: "{{ controller_host }}"
  tags: get_prometheus

- name: Install Prometheus scrapper
  ansible.builtin.unarchive:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-{{ architecture }}.tar.gz"
    dest: /opt/
    remote_src: true
    validate_certs: false
  run_once: true
  delegate_to: "{{ controller_host }}"
  tags: install_prometheus

- name: Create required prometheus directories (I)
  ansible.builtin.file:
    path: /etc/prometheus/
    state: directory
    mode: "0755"
  run_once: true
  delegate_to: "{{ controller_host }}"
  tags: etc_prometheus

- name: Create required prometheus directories (II)
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    mode: "0755"
    owner: prometheus
    group: prometheus
  run_once: true
  delegate_to: "{{ controller_host }}"
  tags: var_prometheus

- name: Deploy configuration for prometheus
  ansible.builtin.template:
    src: prometheus.yaml
    dest: /etc/prometheus/prometheus.yaml
    mode: u=rw,g=r,o=-rwx
  run_once: true
  delegate_to: "{{ controller_host }}"
  tags: config_prometheus

- name: Deploy systemd unit for prometheus-node-exporter
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    mode: u=rw,g=r,o=-rwx
  run_once: true
  delegate_to: "{{ controller_host }}"
  tags: systemd_prometheus

- name: Restart prometheus
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: prometheus
  run_once: true
  delegate_to: "{{ controller_host }}"
  tags: activate_prometheus
