---
- name: Setup NGINX with SSL certificates
  ansible.builtin.import_tasks: nginx.yaml

- name: Services to be setup only on the controller host
  ansible.builtin.import_tasks: metrics.yaml

- name: Services to be setup only on the controller host
  ansible.builtin.import_tasks: controller.yaml
